# Generated by Django 4.1 on 2022-10-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='No Title', max_length=250),
        ),
    ]
